import type { Metadata } from "next";
import { Comfortaa, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Providers } from "./providers";
import Footer from "@/components/Footer";

const ComfortaaFont = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});
const NunitoFont = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${NunitoFont.variable} ${ComfortaaFont.variable} antialiased bg-Grey-08 text-White font-nunito overflow-x-hidden transition-[opacity,background,transform,filter] ease-in-out duration-400`}
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
